<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>slash</string>
	</array>
	<key>name</key>
	<string>Slash</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>\{\#</string>
			<key>comment</key>
			<string>Comments {# like this</string>
			<key>end</key>
			<string>\#\}</string>
			<key>name</key>
			<string>comment.block.slash</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\{%</string>
			<key>comment</key>
			<string>Logic stuff</string>
			<key>end</key>
			<string>%\}</string>
			<key>name</key>
			<string>punctuation.block.tag.slash</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>comment</key>
					<string>Keywords</string>
					<key>match</key>
					<string>(for|in|while|elseif|if|else|empty|extends|include|block|yield|spaceless|end)(?![\t ]*\()</string>
					<key>name</key>
					<string>keyword.control.slash</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#variables</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#SingleQuotedStrings</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#DoubleQuotedStrings</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#numbers</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#booleans</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#ObjectOperator</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comparison</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#assignment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#IncrementDecrement</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#functions</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>\{\{</string>
			<key>comment</key>
			<string>Echoes {{ like so }}</string>
			<key>end</key>
			<string>\}\}</string>
			<key>name</key>
			<string>punctuation.echo.tag.slash</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>comment</key>
					<string>Keyword (or)</string>
					<key>match</key>
					<string>or</string>
					<key>name</key>
					<string>keyword.control.slash</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#variables</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#SingleQuotedStrings</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#DoubleQuotedStrings</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#numbers</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#booleans</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#ObjectOperator</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comparison</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#assignment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#IncrementDecrement</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#functions</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>include</key>
			<string>text.html.basic</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>DoubleQuotedStrings</key>
		<dict>
			<key>begin</key>
			<string>\"</string>
			<key>contentName</key>
			<string>string.quoted.single.slash</string>
			<key>end</key>
			<string>\"</string>
			<key>name</key>
			<string>string.quoted.double.slash</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#escaped</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#wrappedVariables</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#variables</string>
				</dict>
			</array>
		</dict>
		<key>IncrementDecrement</key>
		<dict>
			<key>match</key>
			<string>\+\+|--</string>
			<key>name</key>
			<string>keyword.operator.increment-decrement.slash</string>
		</dict>
		<key>ObjectOperator</key>
		<dict>
			<key>match</key>
			<string>-&gt;</string>
			<key>name</key>
			<string>keyword.operator.class.slash</string>
		</dict>
		<key>SingleQuotedStrings</key>
		<dict>
			<key>begin</key>
			<string>\'</string>
			<key>contentName</key>
			<string>string.quoted.single.slash</string>
			<key>end</key>
			<string>\'</string>
			<key>name</key>
			<string>string.quoted.single.slash</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#escaped</string>
				</dict>
			</array>
		</dict>
		<key>assignment</key>
		<dict>
			<key>match</key>
			<string>[-+]?=</string>
			<key>name</key>
			<string>keyword.operator.assignment.slash</string>
		</dict>
		<key>booleans</key>
		<dict>
			<key>match</key>
			<string>true|false</string>
			<key>name</key>
			<string>constant.language.slash</string>
		</dict>
		<key>comparison</key>
		<dict>
			<key>match</key>
			<string>===?|&gt;|&lt;|&lt;=|&gt;=</string>
			<key>name</key>
			<string>keyword.operator.comparison.slash</string>
		</dict>
		<key>escaped</key>
		<dict>
			<key>match</key>
			<string>\\[^\w]</string>
			<key>name</key>
			<string>constant.character.escape.slash</string>
		</dict>
		<key>functions</key>
		<dict>
			<key>match</key>
			<string>[a-zA-Z_][a-zA-Z_0-9]*</string>
			<key>name</key>
			<string>meta.function-call.slash</string>
		</dict>
		<key>numbers</key>
		<dict>
			<key>match</key>
			<string>\d+</string>
			<key>name</key>
			<string>constant.numeric.slash</string>
		</dict>
		<key>variables</key>
		<dict>
			<key>match</key>
			<string>\$[a-zA-Z_][a-zA-Z0-9_]*</string>
			<key>name</key>
			<string>variable.other.slash</string>
		</dict>
		<key>wrappedVariables</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.variable.slash</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>variable.other.slash</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.variable.slash</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(\{)(\$[a-zA-Z_][a-zA-Z0-9_]*)(\})</string>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>text.html</string>
	<key>uuid</key>
	<string>0da65be4-5aac-4b8f-8071-1aadb970b8d9</string>
</dict>
</plist>
